#!/usr/bin/env bash
# setup_plugin.sh — Create a .venv inside the KiCad plugin directory,
# install kcaa from PyPI, and download the freerouting JAR for the
# auto-router feature.
#
# Run this script from inside the kicad_ai_assistant plugin folder:
#
#   cd ~/.local/share/kicad/10.0/scripting/plugins/kicad_ai_assistant
#   ./setup_plugin.sh

set -euo pipefail

PYTHON_VERSION="3.13"
FREEROUTING_VERSION="2.2.3"
FREEROUTING_JAR="freerouting-${FREEROUTING_VERSION}.jar"
FREEROUTING_URL="https://github.com/freerouting/freerouting/releases/download/v${FREEROUTING_VERSION}/${FREEROUTING_JAR}"

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------
# The script lives inside the plugin directory.
PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$PLUGIN_DIR/.venv"

# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------
if ! command -v uv &>/dev/null; then
    echo "ERROR: uv not found in PATH. Install it from https://github.com/astral-sh/uv"
    exit 1
fi

if ! command -v curl &>/dev/null && ! command -v wget &>/dev/null; then
    echo "ERROR: curl or wget is required to download freerouting. Please install one."
    exit 1
fi

# ---------------------------------------------------------------------------
# Create / update the venv
# ---------------------------------------------------------------------------
echo "Plugin dir : $PLUGIN_DIR"
echo "Venv dir   : $VENV_DIR"
echo ""

echo "Step 1/3 — Creating virtual environment ..."
uv venv "$VENV_DIR" --python "$PYTHON_VERSION"

echo "Step 2/3 — Installing kcaa from PyPI ..."
uv pip install kcaa --python "$VENV_DIR"

echo ""
echo "Step 3/4 — Detecting KiCad configuration ..."

# --- KICAD_VERSION ---
# Extract from plugin directory path
# Expected: ~/.local/share/kicad/10.0/scripting/plugins/kicad_ai_assistant
KICAD_VERSION=""
shopt -s nocasematch
if [[ "$PLUGIN_DIR" =~ /kicad/([0-9]+\.[0-9]+)/ ]]; then
    KICAD_VERSION="${BASH_REMATCH[1]}"
    echo "  Detected KiCad version: $KICAD_VERSION"
else
    echo "  Warning: Could not detect KiCad version from plugin directory path"
    read -p "  Please enter KiCad version (e.g., 10.0): " KICAD_VERSION
    if [[ -z "$KICAD_VERSION" ]]; then
        echo "  Error: KiCad version is required"
        exit 1
    fi
fi
shopt -u nocasematch

# --- Platform-specific default paths ---
if [[ "$OSTYPE" == "darwin"* ]]; then
    DEFAULT_APP_PATH="/Applications/KiCad/KiCad.app"
    KICAD_CONFIG_DIR="$HOME/Library/Preferences/kicad/$KICAD_VERSION"
    KICAD_3RD_PARTY="$HOME/Library/Application Support/kicad/$KICAD_VERSION/3rdparty"
elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
    DEFAULT_APP_PATH="/c/Program Files/KiCad"
    KICAD_CONFIG_DIR="$APPDATA/kicad/$KICAD_VERSION"
    KICAD_3RD_PARTY="$APPDATA/kicad/$KICAD_VERSION/3rdparty"
else
    DEFAULT_APP_PATH="/usr/share/kicad"
    KICAD_CONFIG_DIR="$HOME/.config/kicad/$KICAD_VERSION"
    KICAD_3RD_PARTY="$HOME/.local/share/kicad/$KICAD_VERSION/3rdparty"
fi

# --- KICAD_APP_PATH ---
KICAD_APP_PATH="$DEFAULT_APP_PATH"
if [[ -d "$KICAD_APP_PATH" ]]; then
    echo "  Detected KICAD_APP_PATH: $KICAD_APP_PATH"
else
    echo "  Warning: Default KICAD_APP_PATH not found: $KICAD_APP_PATH"
    read -p "  Please enter KiCad application path: " KICAD_APP_PATH
    KICAD_APP_PATH="${KICAD_APP_PATH/#\~/$HOME}"
    if [[ ! -d "$KICAD_APP_PATH" ]]; then
        echo "  Error: Directory does not exist: $KICAD_APP_PATH"
        exit 1
    fi
fi

# --- Verify KICAD_CONFIG_DIR ---
if [[ -d "$KICAD_CONFIG_DIR" ]]; then
    echo "  Detected KICAD_CONFIG_DIR: $KICAD_CONFIG_DIR"
else
    echo "  Warning: KICAD_CONFIG_DIR not found: $KICAD_CONFIG_DIR"
    read -p "  Please enter KiCad config directory: " KICAD_CONFIG_DIR
    KICAD_CONFIG_DIR="${KICAD_CONFIG_DIR/#\~/$HOME}"
    if [[ ! -d "$KICAD_CONFIG_DIR" ]]; then
        echo "  Error: Directory does not exist: $KICAD_CONFIG_DIR"
        exit 1
    fi
fi

# --- Verify KICAD_3RD_PARTY ---
if [[ -d "$KICAD_3RD_PARTY" ]]; then
    echo "  Detected KICAD_3RD_PARTY: $KICAD_3RD_PARTY"
else
    echo "  Warning: KICAD_3RD_PARTY not found: $KICAD_3RD_PARTY"
    read -p "  Please enter KiCad 3rd-party directory: " KICAD_3RD_PARTY
    KICAD_3RD_PARTY="${KICAD_3RD_PARTY/#\~/$HOME}"
    if [[ ! -d "$KICAD_3RD_PARTY" ]]; then
        echo "  Error: Directory does not exist: $KICAD_3RD_PARTY"
        exit 1
    fi
fi

# --- Generate .env ---
ENV_FILE="$PLUGIN_DIR/.env"
{
    echo "# KiCad AI Assistant environment configuration"
    echo "# Generated by setup_plugin.sh on $(date +%Y-%m-%d)"
    echo ""
    echo "KICAD_VERSION=$KICAD_VERSION"
    echo "KICAD_APP_PATH=$KICAD_APP_PATH"
    echo "KICAD_CONFIG_DIR=$KICAD_CONFIG_DIR"
    echo "KICAD_3RD_PARTY=$KICAD_3RD_PARTY"
} > "$ENV_FILE"

echo ""
echo "  Configuration written to: $ENV_FILE"
echo ""
echo "  Configuration summary:"
echo "    KICAD_VERSION=$KICAD_VERSION"
echo "    KICAD_APP_PATH=$KICAD_APP_PATH"
echo "    KICAD_CONFIG_DIR=$KICAD_CONFIG_DIR"
echo "    KICAD_3RD_PARTY=$KICAD_3RD_PARTY"

echo ""
echo "Step 4/4 — Downloading freerouting JAR ..."
FREEROUTING_DEST="$PLUGIN_DIR/$FREEROUTING_JAR"
if [[ -f "$FREEROUTING_DEST" ]]; then
    echo "  Already present: $FREEROUTING_DEST (skipping download)"
else
    echo "  URL: $FREEROUTING_URL"
    if command -v curl &>/dev/null; then
        curl -fL --progress-bar -o "$FREEROUTING_DEST" "$FREEROUTING_URL"
    else
        wget -q --show-progress -O "$FREEROUTING_DEST" "$FREEROUTING_URL"
    fi
    echo "  Saved to: $FREEROUTING_DEST"
fi

echo ""
echo "Done! The plugin venv is ready at:"
echo "  $VENV_DIR/bin/python"
echo ""
echo "Restart KiCad (or reload the plugin) for the changes to take effect."
